export const INDIA_STATES = [
        "Andhra Pradesh",
        "Arunachal Pradesh",
        "Assam",
        "Bihar",
        "Chhattisgarh",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jharkhand",
        "Karnataka",
        "Kerala",
        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        "Odisha",
        "Punjab",
        "Rajasthan",
        "Sikkim",
        "Tamil Nadu",
        "Telangana",
        "Tripura",
        "Uttar Pradesh",
        "Uttarakhand",
        "West Bengal",
        "Andaman and Nicobar Islands",
        "Chandigarh",
        "Dadra and Nagar Haveli and Daman and Diu",
        "Delhi",
        "Jammu and Kashmir",
        "Ladakh",
        "Lakshadweep",
        "Puducherry",
];

export const INDIA_CITIES_BY_STATE = {
        "Andhra Pradesh": [
                "Visakhapatnam",
                "Vijayawada",
                "Guntur",
                "Nellore",
                "Kurnool",
                "Rajahmundry",
                "Kakinada",
                "Tirupati",
                "Anantapur",
        ],
        "Arunachal Pradesh": [
                "Itanagar",
                "Naharlagun",
                "Pasighat",
                "Roing",
                "Tezu",
        ],
        Assam: [
                "Guwahati",
                "Silchar",
                "Dibrugarh",
                "Jorhat",
                "Nagaon",
                "Tinsukia",
        ],
        Bihar: [
                "Patna",
                "Gaya",
                "Bhagalpur",
                "Muzaffarpur",
                "Purnia",
                "Darbhanga",
        ],
        Chhattisgarh: [
                "Raipur",
                "Bhilai",
                "Bilaspur",
                "Durg",
                "Korba",
                "Raigarh",
        ],
        Goa: [
                "Panaji",
                "Margao",
                "Vasco da Gama",
                "Mapusa",
                "Ponda",
        ],
        Gujarat: [
                "Ahmedabad",
                "Surat",
                "Vadodara",
                "Rajkot",
                "Bhavnagar",
                "Jamnagar",
                "Junagadh",
        ],
        Haryana: [
                "Gurugram",
                "Faridabad",
                "Panipat",
                "Ambala",
                "Hisar",
                "Karnal",
        ],
        "Himachal Pradesh": [
                "Shimla",
                "Mandi",
                "Solan",
                "Dharamshala",
                "Bilaspur",
        ],
        Jharkhand: [
                "Ranchi",
                "Jamshedpur",
                "Dhanbad",
                "Bokaro",
                "Hazaribagh",
        ],
        Karnataka: [
                "Bengaluru",
                "Mysuru",
                "Mangaluru",
                "Hubballi",
                "Belagavi",
                "Shivamogga",
        ],
        Kerala: [
                "Thiruvananthapuram",
                "Kochi",
                "Kozhikode",
                "Thrissur",
                "Kollam",
        ],
        "Madhya Pradesh": [
                "Bhopal",
                "Indore",
                "Jabalpur",
                "Gwalior",
                "Ujjain",
                "Sagar",
        ],
        Maharashtra: [
                "Mumbai",
                "Pune",
                "Nagpur",
                "Nashik",
                "Thane",
                "Aurangabad",
                "Kolhapur",
        ],
        Manipur: [
                "Imphal",
                "Thoubal",
                "Bishnupur",
                "Churachandpur",
        ],
        Meghalaya: [
                "Shillong",
                "Tura",
                "Nongpoh",
        ],
        Mizoram: [
                "Aizawl",
                "Lunglei",
                "Saiha",
        ],
        Nagaland: [
                "Dimapur",
                "Kohima",
                "Mokokchung",
        ],
        Odisha: [
                "Angul",
                "Boudh",
                "Balangir",
                "Kalahandi",
                "Kandhamal",
                "Kendrapara",
                "Cuttack",
                "Jagatsinghpur",
                "Jajpur",
                "Dhenkanal",
                "Deogarh",
                "Nayagarh",
                "Puri",
                "Khordha",
                "Ganjam",
                "Gajapati",
                "Koraput",
                "Rayagada",
                "Malkangiri",
                "Nabarangpur",
                "Nuapada",
                "Bargarh",
                "Jharsuguda",
                "Sambalpur",
                "Sundargarh",
                "Keonjhar",
                "Mayurbhanj",
                "Balasore",
                "Bhadrak",
                "Subarnapur"
                ],

        Punjab: [
                "Ludhiana",
                "Amritsar",
                "Jalandhar",
                "Patiala",
                "Bathinda",
        ],
        Rajasthan: [
                "Jaipur",
                "Jodhpur",
                "Kota",
                "Bikaner",
                "Udaipur",
                "Ajmer",
        ],
        Sikkim: [
                "Gangtok",
                "Namchi",
                "Gyalshing",
        ],
        "Tamil Nadu": [
                "Chennai",
                "Coimbatore",
                "Madurai",
                "Tiruchirappalli",
                "Salem",
                "Erode",
        ],
        Telangana: [
                "Hyderabad",
                "Warangal",
                "Nizamabad",
                "Khammam",
                "Karimnagar",
        ],
        Tripura: [
                "Agartala",
                "Udaipur",
                "Dharmanagar",
        ],
        "Uttar Pradesh": [
                "Lucknow",
                "Kanpur",
                "Varanasi",
                "Agra",
                "Meerut",
                "Prayagraj",
                "Ghaziabad",
        ],
        Uttarakhand: [
                "Dehradun",
                "Haridwar",
                "Haldwani",
                "Rishikesh",
        ],
        "West Bengal": [
                "Kolkata",
                "Howrah",
                "Durgapur",
                "Siliguri",
                "Asansol",
        ],
        "Andaman and Nicobar Islands": [
                "Port Blair",
                "Havelock Island",
                "Diglipur",
        ],
        Chandigarh: [
                "Chandigarh",
        ],
        "Dadra and Nagar Haveli and Daman and Diu": [
                "Daman",
                "Diu",
                "Silvassa",
        ],
        Delhi: [
                "New Delhi",
                "Dwarka",
                "Rohini",
                "Saket",
        ],
        "Jammu and Kashmir": [
                "Srinagar",
                "Jammu",
                "Anantnag",
                "Baramulla",
        ],
        Ladakh: [
                "Leh",
                "Kargil",
        ],
        Lakshadweep: [
                "Kavaratti",
                "Agatti",
                "Minicoy",
        ],
        Puducherry: [
                "Puducherry",
                "Karaikal",
                "Yanam",
                "Mahe",
        ],
};
